"""empty message

Revision ID: 2fab13fce52a
Revises: b8ffd19733f9
Create Date: 2018-03-04 16:42:53.285540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fab13fce52a'
down_revision = 'b8ffd19733f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('user_id', table_name='unverified') WHY
    op.drop_table('unverified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unverified',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('time_created', mysql.DATETIME(), nullable=False),
    sa.Column('time_updated', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='unverified_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'unverified', ['user_id'], unique=True)
    # ### end Alembic commands ###
